service: vega-deployment

frameworkVersion: "3"

package:
  individually: true

plugins:
  - ./resources/Plugin
  - serverless-offline
  - serverless-vpc-plugin
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs16.x
  architecture: arm64
  timeout: 10
  stage: ${file(./.serverlessEnv.yml):STAGE}
  deploymentBucket:
    name: ${vega:s3DeploymentBucket}
  profile: ${file(./.serverlessEnv.yml):AWS_PROFILE}
  httpApi:
    name: ${self:service}-${sls:stage}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:GetItem"
            - "dynamodb:PutItem"
            - "dynamodb:Query"
            - "dynamodb:Scan"
          Resource:
            - arn:aws:dynamodb:us-east-1:${aws:accountId}:table/*
  environment:
    STAGE: ${sls:stage}
    BRANCH: ${file(./.serverlessEnv.yml):BRANCH}
    REDIS_CLUSTER_ENDPOINT: ${vega:redisClusterEndpoint}
    DYNAMO_SFX: ${vega:dynamoSfx}
    BUCKET: ${vega:s3Bucket}
    HOST_ASSETS: ${vega:hostAssets}
    HOST_AUTH: ${vega:hostAuth}
    PWD_SALT: ${ssm:PWD_SALT}
    REGION: ${aws:region}
    SUB_DOMAIN: ${vega:subDomain}
    SUB_DOMAIN_API: ${vega:subDomainApi}

custom:
  env: ${file(./.serverlessEnv.yml)}
  apps: ${file(./resources/Apps.yml):Apps}
  vpcConfig:
    subnetGroups:
      - elasticache
    exportOutputs: true
  esbuild:
    bundle: true
    minify: false

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi: GET /v7/hello
  db:
    handler: handler.db
    events:
      - httpApi: GET /v7/db
  # export:
  #   handler: export.db
  #   timeout: 900
  #   events:
  #     - httpApi: GET /v7/export

resources:
  - ${file(resources/${vega:s3}.yml)}
  - ${file(resources/${vega:dynamoDb}.yml)}
  - ${file(resources/Certificate.yml)}
  - ${file(resources/CloudfrontFunctions.yml)}
  - ${file(resources/CloudfrontCachePolicies.yml)}
  - ${file(resources/CloudfrontDistribution.yml)}
  - ${file(resources/Route53.yml)}
  - ${file(resources/${vega:vpc}.yml)}
  - ${file(resources/${vega:elasticache}.yml)}
