---
Resources:
  #
  # Create SSL Certificate
  #
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-certificatemanager-certificate.html
  #
  # Inspired by:
  # https://hands-on.cloud/aws-cloudformation-how-to-automatically-validate-acm-ssl-certificate/
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: ${vega:certificateDefault}
      SubjectAlternativeNames: ${vega:certificateDomains}
      ValidationMethod: DNS
