---
Resources:
  #
  # Create SSL Certificate
  #
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-certificatemanager-certificate.html
  #
  # Inspired by:
  # https://hands-on.cloud/aws-cloudformation-how-to-automatically-validate-acm-ssl-certificate/
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: "*.dev.playgrnd.media"
      SubjectAlternativeNames:
        - "*.dev.playgrnd.media"
        - "*.dev.baybee.fr"
        - "*.dev.baybee.be"
        - "*.dev.baybee.ch"
        - "*.dev.bidi.boo"
        - "*.dev.bidiboo.com"
        - "*.dev.bidiboo.co.uk"
        - "*.dev.king.pet"
        - "*.dev.kingpet.fr"
        - "*.dev.kingpet.be"
        # - "*.dev.kingpet.ch"
        # - "*.dev.kingpet.com"
        # - "*.dev.kingpet.co.uk"
        # - "*.dev.littlemiss.beauty"
        # - "*.dev.littlemissbeauty.com"
        # - "*.dev.lullapanda.com"
        # - "*.dev.missprincesse.fr"
        # - "*.dev.missprincesse.be"
        # - "*.dev.missprincesse.ch"
        # - "*.dev.pageant.dog"
      ValidationMethod: DNS
