---
Resources:
  #
  # Create Cloudfront Distribution
  #
  # Export an existing cloudfront distribution:
  # aws cloudfront get-distribution-config --id E1VKJ3NZ5SO2Y2 --output yaml
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-distributionconfig.html
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        HttpVersion: http2and3
        PriceClass: PriceClass_100
        Aliases:
          - ${self:custom.subDomainApi}.playgrnd.media
          - ${self:custom.subDomainApi}.bidi.boo
          - ${self:custom.subDomainApi}.dev.baybee.fr"
          - ${self:custom.subDomainApi}.dev.baybee.be"
          - ${self:custom.subDomainApi}.dev.baybee.ch"
          - ${self:custom.subDomainApi}.dev.bidi.boo"
          - ${self:custom.subDomainApi}.dev.bidiboo.com"
          - ${self:custom.subDomainApi}.dev.bidiboo.co.uk"
          - ${self:custom.subDomainApi}.dev.king.pet"
          - ${self:custom.subDomainApi}.dev.kingpet.fr"
          - ${self:custom.subDomainApi}.dev.kingpet.be"
          - ${self:custom.subDomainApi}.dev.kingpet.ch"
          - ${self:custom.subDomainApi}.dev.kingpet.com"
          - ${self:custom.subDomainApi}.dev.kingpet.co.uk"
          - ${self:custom.subDomainApi}.dev.littlemiss.beauty"
          - ${self:custom.subDomainApi}.dev.littlemissbeauty.com"
          - ${self:custom.subDomainApi}.dev.lullapanda.com"
          - ${self:custom.subDomainApi}.dev.missprincesse.fr"
          - ${self:custom.subDomainApi}.dev.missprincesse.be"
          - ${self:custom.subDomainApi}.dev.missprincesse.ch"
          - ${self:custom.subDomainApi}.dev.pageant.dog"
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        # Origins
        Origins:
          - Id: Api Gateway
            DomainName:
              !Join [
                ".",
                [!Ref HttpApi, execute-api, !Ref AWS::Region, amazonaws.com],
              ]
            CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
            OriginShield:
              Enabled: true
              OriginShieldRegion: !Ref AWS::Region
          - Id: Vercel
            DomainName: vega-${sls:stage}.vercel.app
            CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
            OriginShield:
              Enabled: true
              OriginShieldRegion: !Ref AWS::Region
        Enabled: true
        Comment: ${self:service} ${sls:stage}
        #=====================================
        # DefaultCacheBehavior
        #=====================================
        DefaultCacheBehavior:
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          CachedMethods:
            - GET
            - HEAD
          CachePolicyId: !GetAtt CachePolicyAuthStripeHostQs.Id
          Compress: true
          FunctionAssociations:
            - FunctionARN: !GetAtt CloudfrontFunction.FunctionARN
              EventType: "viewer-request"
          TargetOriginId: Api Gateway
          ViewerProtocolPolicy: https-only
        CacheBehaviors:
          # /ph/*
          - PathPattern: "/ph/*"
            AllowedMethods:
              - GET
              - HEAD
            CachedMethods:
              - GET
              - HEAD
            CachePolicyId: !GetAtt CachePolicyLongCacheQsHost.Id
            Compress: true
            FunctionAssociations:
              - FunctionARN: !GetAtt CloudfrontFunction.FunctionARN
                EventType: "viewer-request"
            TargetOriginId: Api Gateway
            ViewerProtocolPolicy: https-only
          #=====================================
          # /v7/a/*
          #=====================================
          - PathPattern: "/v7/a/*"
            AllowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - PATCH
              - POST
              - PUT
            CachedMethods:
              - GET
              - HEAD
            CachePolicyId: !GetAtt CachePolicyGeoHeadersQs.Id
            Compress: true
            FunctionAssociations:
              - FunctionARN: !GetAtt CloudfrontFunction.FunctionARN
                EventType: "viewer-request"
            #ResponseHeadersPolicyId: 5cc3b908-e619-4b99-88e5-2cf7f45965bd #TODO
            TargetOriginId: Api Gateway
            ViewerProtocolPolicy: https-only
          #=====================================
          # /v7/admin/*
          #=====================================
          - PathPattern: "/v7/admin/*"
            AllowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - PATCH
              - POST
              - PUT
            CachedMethods:
              - GET
              - HEAD
            CachePolicyId: !GetAtt CachePolicyGeoHeadersQs.Id
            Compress: true
            FunctionAssociations:
              - FunctionARN: !GetAtt CloudfrontFunction.FunctionARN
                EventType: "viewer-request"
            #ResponseHeadersPolicyId: 5cc3b908-e619-4b99-88e5-2cf7f45965bd #TODO
            TargetOriginId: Api Gateway
            ViewerProtocolPolicy: https-only
          #=====================================
          # /v7/c/*
          #=====================================
          # - PathPattern: "/v7/c/*"
          #   AllowedMethods:
          #     - GET
          #     - HEAD
          #   CachedMethods:
          #     - GET
          #     - HEAD
          #   CachePolicyId: 8445ee16-cda4-4000-b8a3-b1aa80047d20 #TODO
          #   Compress: true
          #   FunctionAssociations:
          #     - FunctionARN: !GetAtt CloudfrontFunction.FunctionARN
          #       EventType: "viewer-request"
          #   ResponseHeadersPolicyId: 5cc3b908-e619-4b99-88e5-2cf7f45965bd #TODO
          #   TargetOriginId: Api Gateway
          #   ViewerProtocolPolicy: https-only
          #=====================================
          # /v7/auth/?et-session
          #=====================================
          # - PathPattern: "/v7/auth/?et-session"
          #   AllowedMethods:
          #     - DELETE
          #     - GET
          #     - HEAD
          #     - OPTIONS
          #     - PATCH
          #     - POST
          #     - PUT
          #   CachedMethods:
          #     - GET
          #     - HEAD
          #   CachePolicyId: CachePolicyGeoHeadersQs.Id
          #   Compress: true
          #   FunctionAssociations:
          #     - FunctionARN: !GetAtt CloudfrontFunction.FunctionARN
          #       EventType: "viewer-request"
          #   ResponseHeadersPolicyId: d433d2a9-5c36-45eb-a99e-a295942cd9f7 #TODO
          #   TargetOriginId: Api Gateway
          #   ViewerProtocolPolicy: https-only
          #=====================================
          # /v7/auth/*
          #=====================================
          - PathPattern: "/v7/auth/*"
            AllowedMethods:
              - GET
              - HEAD
            CachedMethods:
              - GET
              - HEAD
            CachePolicyId: !GetAtt CachePolicyGeoHeadersQs.Id
            Compress: true
            FunctionAssociations:
              - FunctionARN: !GetAtt CloudfrontFunction.FunctionARN
                EventType: "viewer-request"
            TargetOriginId: Api Gateway
            ViewerProtocolPolicy: https-only
          #=====================================
          # /_next/static/*
          #=====================================
          - PathPattern: "/_next/static/*"
            AllowedMethods:
              - GET
              - HEAD
            CachedMethods:
              - GET
              - HEAD
            CachePolicyId: !GetAtt CachePolicyLongCacheQsHost.Id
            Compress: true
            TargetOriginId: Vercel
            ViewerProtocolPolicy: https-only
