---
Resources:
  #
  # Create Vercel Route 53 (sub-domains) records
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html
  #
  BidibooVercelRoute53:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: ${ternary( ${sls:stage}, prod, bidi.boo., dev.bidi.boo. )}
      Comment: ${sls:stage}
      Name: ${self:custom.subDomain}.bidi.boo
      Type: CNAME
      TTL: 300
      ResourceRecords:
        - cname.vercel-dns.com
  #
  # Create Api Route 53 (sub-domains) records
  # Must be set AFTER cloudfront because it uses cloudfront ARN
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html
  #
  BidibooApiRoute53:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: ${ternary( ${sls:stage}, prod, bidi.boo., dev.bidi.boo. )}
      Comment: ${sls:stage} API
      Name: ${self:custom.subDomainApi}.bidi.boo
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2 # Do not change "Specify Z2FDTNDATAQYW2. This is always the hosted zone ID when you create an alias record that routes traffic to a CloudFront distribution."
        DNSName: !GetAtt CloudFrontDistribution.DomainName
  PlaygrndApiRoute53:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: ${ternary( ${sls:stage}, prod, playgrnd.media., dev.playgrnd.media. )}
      Comment: ${sls:stage} API
      Name: ${self:custom.subDomainApi}.playgrnd.media
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2 # Do not change "Specify Z2FDTNDATAQYW2. This is always the hosted zone ID when you create an alias record that routes traffic to a CloudFront distribution."
        DNSName: !GetAtt CloudFrontDistribution.DomainName
