---
Resources:
  #
  # Create Api Route 53 (sub-domains) records
  # Must be set AFTER cloudfront because it uses cloudfront ARN
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html
  #
  PlaygrndApiRoute53:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: ${self:custom.subDomainPfx}bidi.boo.
      Comment: ${sls:stage} API
      Name: ${self:custom.subDomainApi}.playgrnd.media
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudFrontDistribution.DomainName
  BaybeeFrApiRoute53:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: ${self:custom.subDomainPfx}baybee.fr.
      Comment: ${sls:stage} API
      Name: ${self:custom.subDomainApi}.baybee.fr
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudFrontDistribution.DomainName
  BaybeeBeApiRoute53:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: ${self:custom.subDomainPfx}baybee.be.
      Comment: ${sls:stage} API
      Name: ${self:custom.subDomainApi}.baybee.be
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudFrontDistribution.DomainName
  BaybeeChApiRoute53:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: ${self:custom.subDomainPfx}baybee.ch.
      Comment: ${sls:stage} API
      Name: ${self:custom.subDomainApi}.baybee.ch
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudFrontDistribution.DomainName
  BidibooApiRoute53:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: ${self:custom.subDomainPfx}bidi.boo.
      Comment: ${sls:stage} API
      Name: ${self:custom.subDomainApi}.bidi.boo
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudFrontDistribution.DomainName
  BidibooComApiRoute53:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: ${self:custom.subDomainPfx}bidiboo.com.
      Comment: ${sls:stage} API
      Name: ${self:custom.subDomainApi}.bidiboo.com
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudFrontDistribution.DomainName
  BidibooCoUkApiRoute53:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: ${self:custom.subDomainPfx}bidiboo.co.uk.
      Comment: ${sls:stage} API
      Name: ${self:custom.subDomainApi}.bidiboo.co.uk
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudFrontDistribution.DomainName
  KingPetApiRoute53:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: ${self:custom.subDomainPfx}king.pet.
      Comment: ${sls:stage} API
      Name: ${self:custom.subDomainApi}.king.pet
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudFrontDistribution.DomainName
  KingPetFrApiRoute53:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: ${self:custom.subDomainPfx}kingpet.fr.
      Comment: ${sls:stage} API
      Name: ${self:custom.subDomainApi}.kingpet.fr
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudFrontDistribution.DomainName
  KingPetBeApiRoute53:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: ${self:custom.subDomainPfx}kingpet.be.
      Comment: ${sls:stage} API
      Name: ${self:custom.subDomainApi}.kingpet.be
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudFrontDistribution.DomainName
  KingPetChApiRoute53:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: ${self:custom.subDomainPfx}kingpet.ch.
      Comment: ${sls:stage} API
      Name: ${self:custom.subDomainApi}.kingpet.ch
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudFrontDistribution.DomainName
  KingPetComApiRoute53:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: ${self:custom.subDomainPfx}kingpet.com.
      Comment: ${sls:stage} API
      Name: ${self:custom.subDomainApi}.kingpet.com
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudFrontDistribution.DomainName
  KingPetCoUkApiRoute53:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: ${self:custom.subDomainPfx}kingpet.co.uk.
      Comment: ${sls:stage} API
      Name: ${self:custom.subDomainApi}.kingpet.co.uk
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudFrontDistribution.DomainName
  LittleMissBeautyApiRoute53:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: ${self:custom.subDomainPfx}littlemiss.beauty.
      Comment: ${sls:stage} API
      Name: ${self:custom.subDomainApi}.littlemiss.beauty
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudFrontDistribution.DomainName
  LittleMissBeautyComApiRoute53:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: ${self:custom.subDomainPfx}littlemissbeauty.com.
      Comment: ${sls:stage} API
      Name: ${self:custom.subDomainApi}.littlemissbeauty.com
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudFrontDistribution.DomainName
  LullaPandaComApiRoute53:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: ${self:custom.subDomainPfx}lullapanda.com.
      Comment: ${sls:stage} API
      Name: ${self:custom.subDomainApi}.lullapanda.com
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudFrontDistribution.DomainName
  MissPrincesseFrApiRoute53:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: ${self:custom.subDomainPfx}missprincesse.fr.
      Comment: ${sls:stage} API
      Name: ${self:custom.subDomainApi}.missprincesse.fr
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudFrontDistribution.DomainName
  MissPrincesseBeApiRoute53:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: ${self:custom.subDomainPfx}missprincesse.be.
      Comment: ${sls:stage} API
      Name: ${self:custom.subDomainApi}.missprincesse.be
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudFrontDistribution.DomainName
  MissPrincesseChApiRoute53:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: ${self:custom.subDomainPfx}missprincesse.ch.
      Comment: ${sls:stage} API
      Name: ${self:custom.subDomainApi}.missprincesse.ch
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudFrontDistribution.DomainName
  PageantDogApiRoute53:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: ${self:custom.subDomainPfx}pageant.dog.
      Comment: ${sls:stage} API
      Name: ${self:custom.subDomainApi}.pageant.dog
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudFrontDistribution.DomainName
